/**
 * Global Programs Archive content (S11.4) — the 42-item government-program
 * table from crit_r4_global_programs.md. Two independent grading axes per
 * item: DOCUMENTED PROGRAM? (a document says it existed) and VALIDATED
 * EFFECT? (independent, methodologically sound evidence the claimed effect
 * works). A government report asserting plausibility is not validation; a
 * patent proves only that an application was filed.
 *
 * Framing is law here: history & funding — not validation.
 */

import type { Program } from './types';

export const PROGRAMS: readonly Program[] = [
  {
    n: 1,
    name: 'Gateway Report (CIA-RDP96-00788R001700210016-5)',
    country: 'US',
    agency: 'Army INSCOM',
    years: '1983, declassified 2003',
    era: '1980s–90s',
    documented: 'YES-T1',
    validated: 'NO',
    url: 'https://www.cia.gov/readingroom/docs/CIA-RDP96-00788R001700210016-5.pdf',
    verdict: 'Documented assessment ≠ validated effect — zero experiments in the document.',
  },
  {
    n: 2,
    name: 'SCANATE → GRILL FLAME → CENTER LANE → SUN STREAK → STAR GATE',
    country: 'US',
    agency: 'CIA / INSCOM / DIA',
    years: '1972–1995',
    era: '1950s–70s',
    documented: 'YES',
    validated: 'DISPROVED',
    url: 'https://irp.fas.org/program/collect/stargate.htm',
    verdict: 'Documented; effect judged non-actionable as an intelligence tool (AIR 1995). ≈$20M, 23 years.',
    officialNegative: true,
  },
  {
    n: 3,
    name: 'INSCOM–Monroe Hemi-Sync contracts',
    country: 'US',
    agency: 'Army INSCOM',
    years: '~1981–84',
    era: '1980s–90s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://www.theblackvault.com/documentarchive/stargate-collection-analysis-and-assessment-of-gateway-process-9-june-1983/',
    verdict: 'Documented purchase of unproven tech; no published controlled data.',
  },
  {
    n: 4,
    name: 'Frey microwave auditory effect (MAE) research lineage',
    country: 'US',
    agency: 'GE Cornell; USAF/Army/Navy bioeffects labs',
    years: '1960–present',
    era: '1950s–70s',
    documented: 'YES',
    validated: 'YES',
    url: 'https://hackaday.com/2017/09/25/cuban-embassy-attacks-and-the-microwave-auditory-effect/',
    verdict: 'Documented AND validated — but only "hearing clicks" (thermoelastic sensation), not mind control.',
  },
  {
    n: 5,
    name: 'Project PANDORA (Moscow Signal bioeffects)',
    country: 'US',
    agency: 'ARPA/DARPA + Walter Reed',
    years: '1965–1970s',
    era: '1950s–70s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://www.thenation.com/article/world/havana-syndrome-attacks-cia/',
    verdict: 'Documented program; weapon claim failed ("results mixed… not an effective mind-control weapon").',
  },
  {
    n: 6,
    name: 'Moscow Signal itself',
    country: 'USSR → US Embassy',
    agency: 'USSR (transmitter) / US State Dept (monitoring)',
    years: '1953–1976/79',
    era: '1950s–70s',
    documented: 'YES',
    validated: 'NO',
    url: null,
    verdict: 'Documented irradiation; no validated health harm at 5 µW/cm² (Johns Hopkins/Lilienfeld study negative).',
  },
  {
    n: 7,
    name: 'MEDUSA (Mob Excess Deterrent Using Silent Audio)',
    country: 'US',
    agency: 'Navy SBIR → WaveBand → Sierra Nevada',
    years: '2003–2008',
    era: '2000s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://www.wired.com/2007/08/the-other-medus/',
    verdict: 'Documented prototype ($99,965 Phase I); discontinued pre-fielding amid safety doubts — never validated as a safe/effective weapon.',
  },
  {
    n: 8,
    name: '"Bioeffects of Selected Nonlethal Weapons" survey',
    country: 'US',
    agency: 'Army INSCOM',
    years: '1998; declassified 2006 via FOIA',
    era: '1980s–90s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://www.mgr.org/refs/BioeffectsNonLethalWeapons.html',
    verdict: 'Documented feasibility survey ≠ working weapon. Counterweight: Jauchem & Cook (AFRL 2007), "A Lack of Useful Systems".',
    officialNegative: true,
  },
  {
    n: 9,
    name: 'LRAD / acoustic hailing devices',
    country: 'US',
    agency: 'LRAD Corp/Genasys; US military + allied navies',
    years: '2003–present',
    era: '2000s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: 'https://www.naval-technology.com/news/newslrad-to-deliver-acoustic-hailing-devices-to-undisclosed-customer-4298463/',
    verdict: 'Works as a very loud directional loudspeaker; "psychoacoustic weapon" / "Voice of God" claims overstated; no entrainment.',
  },
  {
    n: 10,
    name: 'US Army "synthetic telepathy" MURI',
    country: 'US',
    agency: 'Army Research Office → UC Irvine (D\'Zmura)',
    years: '2008–, $4M',
    era: '2000s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: 'https://medicalxpress.com/news/2008-08-scientists-synthetic-telepathy.html',
    verdict: 'Documented grant; validated only as ordinary, slow, training-intensive EEG BCI. The name outruns the science.',
  },
  {
    n: 11,
    name: 'DoD theta binaural-beat sleep studies (TriService HU0001-16-1-TS02)',
    country: 'US',
    agency: 'DoD / USU',
    years: '2012–2015+',
    era: '2010s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9909225/',
    verdict: 'Documented; weak/modest effect — HRV autonomic shifts p<0.01 (Gantt 2017); sleep-onset efficacy unproven.',
  },
  {
    n: 12,
    name: 'NIA/NCCIH 40 Hz GENUS (R01AG069232, R01AT011460)',
    country: 'US',
    agency: 'NIH → MIT Tsai lab',
    years: '2021–',
    era: '2020s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: 'https://pubmed.ncbi.nlm.nih.gov/36879142/',
    verdict: 'Documented; validation pending — mouse efficacy contested (Soula 2023; Yang & Lai 2023; Cognito OVERTURE missed primary), human Phase III readout ~2026.',
  },
  {
    n: 13,
    name: 'DARPA TNT sleep targeted-memory-reactivation arm',
    country: 'US',
    agency: 'DARPA BTO (Teledyne et al.)',
    years: '2016–~2021',
    era: '2010s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: null,
    verdict: 'Documented; modest validated cueing effect (~40% faster navigation after acoustic cueing in SWS, single paradigm).',
  },
  {
    n: 14,
    name: 'DARPA RadioBio',
    country: 'US',
    agency: 'DARPA',
    years: '2017–2021',
    era: '2010s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://militaryembedded.com/news/radiobio-research-effort-aims-to-find-the-role-of-electromagnetic-signaling-in-biological-systems/',
    verdict: 'Documented exploration; no demonstrated purposeful EM cell-to-cell signaling — a modern null on the Pandora question.',
  },
  {
    n: 15,
    name: 'CIA MKULTRA subprojects incl. RF/primate cerebral activity',
    country: 'US',
    agency: 'CIA',
    years: '1953–1964+',
    era: '1950s–70s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://www.thenation.com/article/world/havana-syndrome-attacks-cia/',
    verdict: 'Documented program (1977 Senate hearings); no operational mind control ever demonstrated.',
  },
  {
    n: 16,
    name: 'Soviet parapsychology / telepathy labs (Bekhterev Institute, Vasilyev)',
    country: 'USSR',
    agency: 'State-funded (1920s–1937; revived ~1960)',
    years: '1920s–1980s',
    era: '1950s–70s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://ar5iv.labs.arxiv.org/html/1312.1148',
    verdict: 'Documented programs; effects never replicated — Vasilyev himself rejected the EM-carrier hypothesis by 1937.',
  },
  {
    n: 17,
    name: 'LIDA device (US Patent 3,773,049)',
    country: 'USSR (Soviet Armenia)',
    agency: 'Rabichev et al.; Adey evaluation (US)',
    years: '1950s–1970s',
    era: '1950s–70s',
    documented: 'YES-T1',
    validated: 'NO',
    url: 'https://patents.google.com/patent/US3773049',
    verdict: 'Documented device + 740-patient Soviet claim; zero independent validation — Adey "had not tested the instrument yet" (1978). Patent ≠ efficacy.',
  },
  {
    n: 18,
    name: 'DIA psychotronics assessments (DST-1810S-387-75; DST-1810S-202-78)',
    country: 'US',
    agency: 'DIA (assessing USSR/Warsaw Pact)',
    years: '1972, 1975, 1978',
    era: '1950s–70s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://www.secretintelligenceservice.org/wp-content/uploads/2015/07/SIS.org-PSYCHOTRONICS-%E2%80%93-SUMMARY-DIA.pdf',
    verdict: 'Documented monitoring of unvalidated claims; analysts graded threat potential, not effects.',
  },
  {
    n: 19,
    name: 'Torsion-field program (Akimov/Shipov, Center for Nontraditional Technologies)',
    country: 'USSR → Russia',
    agency: 'State sponsorship; Min. Science 1992–95; Min. Defense 1996–97',
    years: '1980s–1997',
    era: '1980s–90s',
    documented: 'YES',
    validated: 'DISPROVED',
    url: 'https://overclassified.org/key-figures.html',
    verdict: 'DISPROVED — USSR Academy 1991 inquiry found fraud/embezzlement (~500M rubles, no genuine scientific grounding); the clearest case of state-funded pseudoscience.',
  },
  {
    n: 20,
    name: 'Russian "On Weapons" amendment (EM / infrasonic / ultrasonic limits)',
    country: 'Russia',
    agency: 'State Duma, signed by Putin',
    years: '2001',
    era: '2000s',
    documented: 'YES',
    validated: 'NA',
    url: 'https://www.pravovik24.ru/codes/fz-rf-150/150-st-6/',
    verdict: 'Documented law (FZ-150 art. 6); regulates civilian circulation, exempts state use — legislating against a weapon does not establish it exists.',
  },
  {
    n: 21,
    name: 'Smirnov "psychocorrection" (subliminal EEG-guided audio)',
    country: 'USSR/Russia → US',
    agency: 'Inst. of Psycho-Correlations; FBI consultation 1993; DHS-linked contract 2009',
    years: '1980s–2005',
    era: '1980s–90s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://www.wired.com/2007/09/mind-reading/',
    verdict: 'Documented marketing (incl. Waco consultation); FBI declined, DHS testing produced no validated screening capability.',
  },
  {
    n: 22,
    name: 'China Brain Project (Brain Science & Brain-Inspired Intelligence)',
    country: 'China',
    agency: '13th/14th Five-Year Plans',
    years: '2017–; ~¥5B (~$746M) in 14th FYP',
    era: '2010s',
    documented: 'YES',
    validated: 'NA',
    url: 'https://ndupress.ndu.edu/Media/News/News-Article-View/Article/2846343/chinas-new-generation-ai-brain-project/',
    verdict: 'Documented civilian-state research megaprogram — not an effect claim; no entrainment component identified.',
  },
  {
    n: 23,
    name: 'China NSFC / National Key R&D 40 Hz sensory-entrainment grants',
    country: 'China',
    agency: 'NSFC / NKRDP (2022YFE0199300; NSFC 82571603)',
    years: '2022–',
    era: '2020s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: null,
    verdict: 'Documented CIVILIAN funding (animal/early human work; no validated clinical effect); no military audio-entrainment program found.',
  },
  {
    n: 24,
    name: 'PLA cognitive-warfare / BCI ecosystem (AMS, NUDT, CMC S&TC)',
    country: 'China',
    agency: 'Military-civil fusion',
    years: '2010s–',
    era: '2010s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: 'https://www.biospectrumasia.com/analysis/30/26823/mind-over-matter-decoding-chinas-bci-push.html',
    verdict: 'BCI demos real (brain-controlled drones); "cognitive dominance" is doctrine, not a validated weapon.',
  },
];

export const PROGRAMS_B: readonly Program[] = [
  {
    n: 25,
    name: 'UK MoD remote-viewing study',
    country: 'UK',
    agency: 'Ministry of Defence',
    years: '2001–02; FOI release 2007',
    era: '2000s',
    documented: 'YES',
    validated: 'DISPROVED',
    url: 'https://www.acampbell.org.uk/serendipity/index.php?/archives/234-MOD-funds-research-on-remote-viewing.html',
    verdict: 'Documented program with an officially NEGATIVE result — 28% hit rate vs ~25% chance judged failure; abandoned (£18,000, 168-page report).',
    officialNegative: true,
  },
  {
    n: 26,
    name: 'UK MoD/Dstl audio-entrainment or psychotronics program',
    country: 'UK',
    agency: 'MoD / Dstl',
    years: '—',
    era: '2020s',
    documented: 'NEGATIVE',
    validated: 'NA',
    url: null,
    verdict: 'NEGATIVE RESULT — none found across 6+ targeted searches; absence-of-evidence statement, not proof of absence.',
  },
  {
    n: 27,
    name: 'Defra low-frequency-noise research (NANR45, Salford)',
    country: 'UK',
    agency: 'Defra → University of Salford',
    years: '~2001–2011',
    era: '2000s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: 'https://acoustics.salford.ac.uk/psychoacoustics/low-frequency-noise/',
    verdict: 'Documented environmental-health research: LFN annoyance near audibility is real; no special "infrasound weapon" physiology.',
  },
  {
    n: 28,
    name: 'UBA infrasound experimental study',
    country: 'Germany',
    agency: 'Umweltbundesamt',
    years: '2020',
    era: '2020s',
    documented: 'YES',
    validated: 'NEGATIVE',
    url: 'https://www.umweltbundesamt.de/en/press/pressinformation/infrasound-at-under-perception-threshold-does-not',
    verdict: '44 subjects, 3–18 Hz at 85–105 dB: NO significant acute physiological effects at/below threshold — evidence of absence for acute sub-threshold infrasound claims.',
    officialNegative: true,
  },
  {
    n: 29,
    name: 'TremAc wind-turbine infrasound project',
    country: 'Germany',
    agency: 'Multi-institute, publicly funded',
    years: '~2016–2020',
    era: '2010s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: null,
    verdict: 'Documented measurement science; no validated health harm.',
  },
  {
    n: 30,
    name: 'Bundeswehr infrasound/psychotronics program',
    country: 'Germany',
    agency: 'Bundeswehr',
    years: '—',
    era: '2020s',
    documented: 'NEGATIVE',
    validated: 'NA',
    url: null,
    verdict: 'NEGATIVE RESULT — no open-source evidence of any German military entrainment or infrasound-weapon program.',
  },
  {
    n: 31,
    name: 'EU Human Brain Project (FET Flagship) → EBRAINS',
    country: 'EU',
    agency: 'DG CONNECT',
    years: '2013–2023; €607M EU (~€1B total)',
    era: '2010s',
    documented: 'YES',
    validated: 'NA',
    url: 'https://www.humanbrainproject.eu/en/follow-hbp/news/2023/09/28/human-brain-project-ends-what-has-been-achieved/',
    verdict: 'Documented infrastructure megaproject (155 institutions); no entrainment or weapon component.',
  },
  {
    n: 32,
    name: 'European Parliament Resolution A4-0005/99 (¶27, ¶30)',
    country: 'EU',
    agency: 'European Parliament',
    years: '28 Jan 1999',
    era: '1980s–90s',
    documented: 'YES',
    validated: 'NA',
    url: 'http://www.europarl.europa.eu/sides/getDoc.do?pubRef=-//EP//TEXT+REPORT+A4-1999-0005+0+DOC+XML+V0//EN',
    verdict: 'Documented resolution calling to ban "manipulation of human beings" tech; non-binding, never implemented, presupposes unproven capabilities.',
  },
  {
    n: 33,
    name: 'NATO RTO-TR-SAS-040 non-lethal weapons assessment',
    country: 'NATO',
    agency: 'NATO RTO',
    years: '2004',
    era: '2000s',
    documented: 'YES',
    validated: 'NO',
    url: 'https://scienceandglobalsecurity.org/archive/sgs09altmann.pdf',
    verdict: 'Documented alliance assessment debunking acoustic-weapon hype: "Most are of uncertain effectiveness" (Altmann 2001: infrasound/audio claims "do not stand critical appraisal").',
    officialNegative: true,
  },
  {
    n: 34,
    name: 'Japan Brain/MINDS → Brain/MINDS 2.0; Moonshot Goal 1',
    country: 'Japan',
    agency: 'AMED / RIKEN CBS; Cabinet Office / JST',
    years: '2014–',
    era: '2010s',
    documented: 'YES',
    validated: 'NA',
    url: 'https://www.neurofounders.co/deep-dives/inside-japans-neurotech-scene',
    verdict: 'Documented civilian-state program (marmoset mapping, digital brain); no entrainment weapon found.',
  },
  {
    n: 35,
    name: 'Japan Ministry of Environment low-frequency sound guidance',
    country: 'Japan',
    agency: 'Ministry of the Environment',
    years: '2004',
    era: '2000s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: null,
    verdict: 'Documented environmental complaint-handling policy.',
  },
  {
    n: 36,
    name: 'Korea Brain Initiative',
    country: 'South Korea',
    agency: 'MSIP',
    years: '2016–; ~₩1.3T (~$1.2B) planned 2017–2022',
    era: '2010s',
    documented: 'YES',
    validated: 'NA',
    url: 'http://www.incf.org/partners/korea-brain-initiative-kbri',
    verdict: 'Documented civilian research program.',
  },
  {
    n: 37,
    name: 'Korea MOTIE BCI rehabilitation grant (Ybrain)',
    country: 'South Korea',
    agency: 'MOTIE',
    years: '2025–2027, ~₩6B (~$4.6M)',
    era: '2020s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: null,
    verdict: 'Documented civilian-medical device development; not yet a validated therapy.',
  },
  {
    n: 38,
    name: 'DRDO DIPAS/HAMRC yoga for high-altitude soldiers',
    country: 'India',
    agency: 'DRDO',
    years: '2000s–',
    era: '2000s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: 'https://www.proquest.com/scholarly-journals/study-effect-yoga-practices-on-indian-army-ladakh/docview/1615264262/se-2',
    verdict: 'Documented program; effects are exercise-level (cold/altitude tolerance) — yoga ≠ brainwave tech; do not let DRDO citations launder entrainment claims.',
  },
  {
    n: 39,
    name: 'Israel MoD Neurotechnology Department collaborations',
    country: 'Israel',
    agency: 'Ministry of Defense',
    years: '2020s',
    era: '2020s',
    documented: 'YES',
    validated: 'PARTIAL',
    url: 'https://english.tau.ac.il/research/spinal-cord-injuries',
    verdict: 'Documented biomedical TBI research; no public entrainment program found (negative on that axis).',
  },
  {
    n: 40,
    name: 'France Defence Ethics Committee "augmented soldier" opinion',
    country: 'France',
    agency: 'Ministry of Armed Forces',
    years: '8 Dec 2020',
    era: '2020s',
    documented: 'YES',
    validated: 'NA',
    url: 'https://eandt.theiet.org/2020/12/10/french-army-gets-green-light-bionic-soldiers',
    verdict: 'Documented policy green-light for cognitive-enhancement research — governance instrument, not an existing capability; invasive brain modification excluded for now.',
  },
  {
    n: 41,
    name: 'WHO–ITU Make Listening Safe / ITU-T H.870, H.871, H.872 + WHA70.13',
    country: 'WHO/ITU (UN system)',
    agency: 'WHO / ITU',
    years: '2015– (H.870 2018; v2 2022; gaming 2025)',
    era: '2010s',
    documented: 'YES',
    validated: 'YES',
    url: 'https://www.efhoh.org/wp-content/uploads/2021/04/ITU-Standard-Safe-Listening-Devices-T-REC-H.870-201808-IPDF-E.pdf',
    verdict: 'The strongest VALIDATED government sound-brain contribution: hearing-loss dose science — protective, not enhancement.',
  },
  {
    n: 42,
    name: 'WHO global standard for safe listening venues/events',
    country: 'WHO (ITU-adopted 2024)',
    agency: 'WHO / ITU',
    years: '2019–2024',
    era: '2020s',
    documented: 'YES',
    validated: 'YES',
    url: 'https://efhoh.org/2025/06/itu-who-global-standard-for-safe-listening-in-video-gameplay-and-esports-officially-adopted/',
    verdict: 'As above — validated protective regulation resting on real dose-response science.',
  },
];

export const ALL_PROGRAMS: readonly Program[] = [...PROGRAMS, ...PROGRAMS_B];

/** Mandatory framing banner (S11.4 AC). */
export const PROGRAMS_BANNER =
  'HISTORY & FUNDING — NOT VALIDATION. A document proves a program existed; it does not prove the effect works. Government money has flowed to real science, to null results, and to outright fraud alike — graded on two independent axes below.';

/** Torsion-field fraud case card (R4 synthesis #2). */
export const TORSION_CASE = {
  title: 'Case study: torsion fields — state-funded pseudoscience, officially found fraudulent',
  body: 'Akimov & Shipov\'s state-sponsored Center for Nontraditional Technologies (Moscow, late 1980s) claimed "torsion/spinor fields" enabling FTL communication, medical effects and antigravity. The USSR Academy of Sciences\' 1991 inquiry — after Yevgeny Aleksandrov\'s General Meeting denunciation — found ~500 million rubles (~$7M) drawn from multiple state ministries with no genuine scientific grounding; the center was disbanded. The same actors were then RE-funded by the Russian Ministry of Science (1992–95) and Ministry of Defense (1996–97).',
  lesson:
    'The gold-standard example that documented ≠ validated: here the state itself issued the fraud verdict — and kept paying.',
  url: 'https://overclassified.org/key-figures.html',
};

/** Official negative results — the strongest debunking assets (R4 synthesis #4). */
export const OFFICIAL_NEGATIVES_NOTE =
  'Official negative results are the strongest debunking assets in the archive: UK MoD 2001–02 (remote viewing judged failure), UBA 2020 (no acute sub-threshold infrasound effects in a controlled experiment), AFRL 2007 (Jauchem & Cook: "A Lack of Useful Systems" for acoustic non-lethal weapons), AIR 1995 (23 years of operational remote viewing never actionable), NATO 2004 ("uncertain effectiveness").';
